start cmd /c "javac *.java"
start cmd /k "java Echo"
start cmd /k "java Reverse"
start cmd /k "java Upper"
start cmd /k "java Lower"
start cmd /k "java Ceaser"
start cmd /k "java Mystery"
start cmd /k "java Master 6666"
start cmd /k "java Client 6666 localhost"